// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: pb/string.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StringRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	A             string                 `protobuf:"bytes,1,opt,name=A,proto3" json:"A,omitempty"`
	B             string                 `protobuf:"bytes,2,opt,name=B,proto3" json:"B,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StringRequest) Reset() {
	*x = StringRequest{}
	mi := &file_pb_string_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StringRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StringRequest) ProtoMessage() {}

func (x *StringRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pb_string_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StringRequest.ProtoReflect.Descriptor instead.
func (*StringRequest) Descriptor() ([]byte, []int) {
	return file_pb_string_proto_rawDescGZIP(), []int{0}
}

func (x *StringRequest) GetA() string {
	if x != nil {
		return x.A
	}
	return ""
}

func (x *StringRequest) GetB() string {
	if x != nil {
		return x.B
	}
	return ""
}

type StringResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ret           string                 `protobuf:"bytes,1,opt,name=Ret,proto3" json:"Ret,omitempty"`
	Err           string                 `protobuf:"bytes,2,opt,name=err,proto3" json:"err,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StringResponse) Reset() {
	*x = StringResponse{}
	mi := &file_pb_string_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StringResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StringResponse) ProtoMessage() {}

func (x *StringResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pb_string_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StringResponse.ProtoReflect.Descriptor instead.
func (*StringResponse) Descriptor() ([]byte, []int) {
	return file_pb_string_proto_rawDescGZIP(), []int{1}
}

func (x *StringResponse) GetRet() string {
	if x != nil {
		return x.Ret
	}
	return ""
}

func (x *StringResponse) GetErr() string {
	if x != nil {
		return x.Err
	}
	return ""
}

var File_pb_string_proto protoreflect.FileDescriptor

const file_pb_string_proto_rawDesc = "" +
	"\n" +
	"\x0fpb/string.proto\x12\x02pb\"+\n" +
	"\rStringRequest\x12\f\n" +
	"\x01A\x18\x01 \x01(\tR\x01A\x12\f\n" +
	"\x01B\x18\x02 \x01(\tR\x01B\"4\n" +
	"\x0eStringResponse\x12\x10\n" +
	"\x03Ret\x18\x01 \x01(\tR\x03Ret\x12\x10\n" +
	"\x03err\x18\x02 \x01(\tR\x03err2s\n" +
	"\rStringService\x121\n" +
	"\x06Concat\x12\x11.pb.StringRequest\x1a\x12.pb.StringResponse\"\x00\x12/\n" +
	"\x04Diff\x12\x11.pb.StringRequest\x1a\x12.pb.StringResponse\"\x00B\x06Z\x04.;pbb\x06proto3"

var (
	file_pb_string_proto_rawDescOnce sync.Once
	file_pb_string_proto_rawDescData []byte
)

func file_pb_string_proto_rawDescGZIP() []byte {
	file_pb_string_proto_rawDescOnce.Do(func() {
		file_pb_string_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pb_string_proto_rawDesc), len(file_pb_string_proto_rawDesc)))
	})
	return file_pb_string_proto_rawDescData
}

var file_pb_string_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_pb_string_proto_goTypes = []any{
	(*StringRequest)(nil),  // 0: pb.StringRequest
	(*StringResponse)(nil), // 1: pb.StringResponse
}
var file_pb_string_proto_depIdxs = []int32{
	0, // 0: pb.StringService.Concat:input_type -> pb.StringRequest
	0, // 1: pb.StringService.Diff:input_type -> pb.StringRequest
	1, // 2: pb.StringService.Concat:output_type -> pb.StringResponse
	1, // 3: pb.StringService.Diff:output_type -> pb.StringResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_pb_string_proto_init() }
func file_pb_string_proto_init() {
	if File_pb_string_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pb_string_proto_rawDesc), len(file_pb_string_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pb_string_proto_goTypes,
		DependencyIndexes: file_pb_string_proto_depIdxs,
		MessageInfos:      file_pb_string_proto_msgTypes,
	}.Build()
	File_pb_string_proto = out.File
	file_pb_string_proto_goTypes = nil
	file_pb_string_proto_depIdxs = nil
}
